# Generated by Django 4.1.3 on 2022-12-23 19:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryP',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('thumbnailp', models.ImageField(default=False, upload_to='thumbnail/')),
            ],
            options={
                'db_table': 'CPhotos',
            },
        ),
        migrations.CreateModel(
            name='CategoryV',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('thumbnailv', models.ImageField(default=False, upload_to='thumbnail/')),
            ],
            options={
                'db_table': 'CVideos',
            },
        ),
        migrations.CreateModel(
            name='P_Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 23, 20, 19, 53, 516411))),
            ],
            options={
                'db_table': 'Picture Posts',
            },
        ),
        migrations.CreateModel(
            name='V_Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='post_videos')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 23, 20, 19, 53, 517410))),
            ],
            options={
                'db_table': 'Video Posts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(default=False, upload_to='profile_images')),
                ('location', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User Accounts',
            },
        ),
    ]
